name: "KiCad actions"
description: "A GitHub action that can generate and check KiCad schematics and PCBs."
branding:
  icon: "cpu"
  color: "green"

inputs:
  # Schematic input file
  schematic_file_name:
    description: "Location of the '.kicad_sch' file."

  # Symbol library file
  symbol_libraries:
    description: "Comma-separated list of symbol libraries in the format name=path."

  # ERC run
  run_erc:
    description: "Run the ERC on the schematic."
    default: false

  erc_output_file_name:
    description: "Output file name of ERC report."
    default: "erc.rpt"

  # Schematic PDF output
  schematic_output_pdf:
    description: "Run the PDF export of the schematic."
    default: false

  schematic_output_pdf_file_name:
    description: "Output file name of PDF schematic."
    default: "schematic.pdf"

  schematic_output_black_white:
    description: "Run the PDF, SVG, DXF and PS schematic export in black and white."
    default: false

  # Schematic SVG output
  schematic_output_svg:
    description: "Run the SVG export of the schematic."
    default: false

  schematic_output_svg_folder_name:
    description: "Output folder name of SVG schematic."
    default: "schematics"

  # Schematic DXF output
  schematic_output_dxf:
    description: "Run the DXF export of the schematic."
    default: false

  schematic_output_dxf_folder_name:
    description: "Output folder name of DXF schematic."
    default: "schematics"

  # Schematic HPGL output
  schematic_output_hpgl:
    description: "Run the HPGL export of the schematic."
    default: false

  schematic_output_hpgl_folder_name:
    description: "Output folder name of HPGL schematic."
    default: "schematics"

  # Schematic PS output
  schematic_output_ps:
    description: "Run the PS export of the schematic."
    default: false

  schematic_output_ps_folder_name:
    description: "Output folder name of PS schematic."
    default: "schematics"

  # Schematic BOM output
  schematic_output_bom:
    description: "Run the BOM export of the schematic."
    default: false

  schematic_output_bom_file_name:
    description: "Output file name of the BOM."
    default: "bom.csv"

  schematic_output_bom_fields:
    description: "Output fields in the BOM file. `*` includes all fields."
    default: "Reference,Value,Footprint,${QUANTITY},${DNP}"

  schematic_output_bom_labels:
    description: "Output labels in the BOM file."
    default: "Refs,Value,Footprint,Qty,DNP"

  # Schematic netlist output
  schematic_output_netlist:
    description: "Run the netlist export of the schematic."
    default: false

  schematic_output_netlist_file_name:
    description: "Output file name of the netlist."
    default: "netlist.net"

  # PCB input file
  pcb_file_name:
    description: "Location of the '.kicad_pcb' file."

  # Footprint library file
  footprint_libraries:
    description: "Comma-separated list of footprint libraries in the format name=path."

  # DRC run
  run_drc:
    description: "Run the DRC on the PCB."
    default: false

  drc_output_file_name:
    description: "Output file name of DRC report."
    default: "drc.rpt"

  # PCB drill output
  pcb_output_drill:
    description: "Run the drill export of the PCB."
    default: false

  pcb_output_drill_folder_name:
    description: "Output folder name of drill file."
    default: "drill"

  pcb_output_drill_format:
    description: "Format of the drill file. Options: 'excellon', 'gerber'."
    default: "excellon"

  # PCB gerbers output
  pcb_output_gerbers:
    description: "Run the gerber export of the PCB."
    default: false

  pcb_output_gerbers_folder_name:
    description: "Output folder name of gerber files."
    default: "gerbers"

  pcb_output_layers:
    description: "Output layers of the PCB."

  # PCB gerbers and drill output
  pcb_output_gerbers_and_drill:
    description: "Run the gerber and drill export of the PCB."
    default: false

  pcb_output_gerbers_and_drill_folder_name:
    description: "Output folder name of gerber and drill files."
    default: "gerbers"

  # Pcb DXF output
  pcb_output_dxf:
    description: "Run the DXF export of the PCB."
    default: false

  pcb_output_dxf_folder_name:
    description: "Output folder name of DXF PCB."
    default: "dxf"

  # Pcb PDF output
  pcb_output_pdf:
    description: "Run the PDF export of the PCB."
    default: false

  pcb_output_pdf_file_name:
    description: "Output file name of PDF PCB."
    default: "pcb.pdf"

  pcb_output_black_white:
    description: "Run the PDF and SVG PCB export in black and whit."
    default: false

  # Pcb SVG output
  pcb_output_svg:
    description: "Run the SVG export of the PCB."
    default: false

  pcb_output_svg_file_name:
    description: "Output file name of SVG PCB."
    default: "pcb.svg"

  # Pcb POS output
  pcb_output_pos:
    description: "Run the POS export of the PCB."
    default: false

  pcb_output_pos_file_name:
    description: "Output file name of POS PCB."
    default: "pcb.pos"

  pcb_output_pos_format:
    description: "Format of the pos file. Options: 'ascii', 'csv', 'gerber'."
    default: "ascii"

  pcb_output_pos_side:
    description: "Side of the post file. Options: 'front', 'back', 'both'. Both is not supported by gerber."
    default: "both"

  # PCB IPC-2581 output
  pcb_output_ipc2581:
    description: "Run the IPC-2581 export of the PCB."
    default: false

  pcb_output_ipc2581_file_name:
    description: "Output file name of IPC-2581 PCB."
    default: "pcb.xml"

  # PCB STEP output
  pcb_output_step:
    description: "Run the STEP export of the PCB."
    default: false

  pcb_output_step_file_name:
    description: "Output file name of STEP PCB."
    default: "pcb.step"

  # PCB image output
  pcb_output_image:
    description: "Run the image export of the PCB."
    default: false

  pcb_output_image_file_name:
    description: "Output file name of image PCB. Must end in '.png', '.jpg', '.jpeg'."
    default: "pcb.png"

  pcb_output_image_side:
    description: "Side of the image PCB. Options: 'top', 'bottom', 'left', 'right', 'front', 'back'."
    default: "top"

  pcb_output_image_background:
    description: "Background of the image PCB. Options: 'default', 'transparent', 'opaque'. For PNG files, default is transparent. For JPG files, default is opaque."
    default: "default"

  pcb_output_image_width:
    description: "Width of the image PCB in pixels."
    default: "1600"

  pcb_output_image_height:
    description: "Height of the image PCB in pixels."
    default: "900"

  pcb_output_image_floor:
    description: "Enables floor, shadows and post-processing."
    default: false

runs:
  using: "docker"
  image: "Dockerfile"
